# FROM python:alpine3.20
# FROM python:slim-bullseye
FROM python:3

COPY tools .
# COPY app/cleaning.sh /usr/src/app/

RUN pip install -r requirements.txt

RUN chmod +x entrypoint.sh

WORKDIR /usr/src/app


ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]