# Generated by Django 5.0.6 on 2024-06-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, default='uploads/avatar.png', null=True, upload_to='avatars'),
        ),
    ]
