# Generated by Django 5.0.6 on 2024-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_notification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='accepter_id',
            new_name='accepter',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('sender', 'accepter')},
        ),
    ]
